### ISSUE TITLE
socket.decoded_token undefined in namespace 

### ISSUE THREAD

**Issue by zpiman** [auth0/socketio-jwt#30]
socket.decoded_token works well when used on the default name space: 
```javascript
io.on("connection", function(socket) {
   console.log(socket.decoded_token) // Returns the decoded toke
});
```
However this does not work:
```javascript

var nsp = io.of('/someNamespace');
nsp.on("connection", function(socket) {
   console.log(socket.decoded_token) // undefined 
});
```

My best guess is that the object is not cloned exactly. I am not sure there is any fix for this. This seems to be a socket.io internal problem. However to utilize the entire power of the combination of **JWT** and **SocketIO** namespaces, this feature should be added.

**Comment by fiims3004** [comment]
Default namespace '/'
io.use(socketioJwt.authorize({
      secret: 'your secret',
      handshake: true
}));
Custom namespace:
io.of('/custom-nsp').use(socketioJwt.authorize({
      secret: 'your secret',
      handshake: true
}));

**Comment by zpiman** [comment]
A little redundant but works!

**Comment by mgonto** [comment]
Hey,

You could do what @fiims3004 is saying but actually extract what the call to `socketioJwt.authorize` returns. Something like:

````js
var authorizer = socketioJwt.authorize({
secret: 'your secret',
handshake: true
});
// Default namespace '/'
io.use(authorizer);
// Custom namespace:
io.of('/custom-nsp').use(authorizer);
````

Let me know if it helps!

Cheers!
