### ISSUE TITLE
On socket reconnection there's no notification if verification fails/expires

### ISSUE THREAD

**Issue by maruf89** [auth0/socketio-jwt#33]
Here's my issue:

1. User signs in & get's a newly created token
2. Token expires, but the client is still connected, and everything continues to function the same as if their token hadn't expired
3. Server restarts causing the connection to be terminated (shouldn't matter from which end)
4. Client tries to reconnect to the server with the same token which has expired.
5. Wait eternally as the error fails silently...

Couldn't we get some notification for a failed reconnect or something? Right now the only way I can check is to detect a reconnect (because I've bound 1 secure and 1 insecure socket, so the insecure socket still reconnects) -> send a test request to the secure socket -> set a timeout -> if the timeout expires without a response then I know something failed.

**Comment by maruf89** [comment]
How do you delete this damn thing?

**Comment by jfromaniello** [comment]
I think you cant, but why do you want to delete it?

how you solve the issue?

**Comment by maruf89** [comment]
I realized I had the `.on('error')` set to `once`, (then I deleted my bug), but even with change that I only sometimes got the error. Now I'm doing a ping/pong check to the server with a 5 second timeout. If I don't get a response back I assume the token has timeout and I downgrade the socket connection
