### ISSUE TITLE
Expiration of socketio.jwt in your example code seems not working.

### ISSUE THREAD

**Issue by wang3g** [auth0/socketio-jwt#38]
I ported your example code (https://github.com/auth0/socketio-jwt/tree/master/example) into a small, clean project. Everything looks fine except that the token seems never expired.

I changed 
var token = jwt.sign(profile, jwt_secret, { expiresInMinutes: 60*5 });
to
var token = jwt.sign(profile, jwt_secret, { expiresInMinutes: 2});

After 2 minutes, "--broadcast: Tue Mar 24 2015 14:15:25 GMT+1100 (AUS Eastern Daylight Time) " still keeps popping out. And if  clicking 'Send socket.io ping' button, I can see 
"- ping
- pong ".

I also checked socket.decoded_token.exp. There is a valid time stamp on it. So what did I do wrong?  Below is my config:

  "dependencies": {
    "body-parser": "^1.9.0",
    "express": "~4.9.0",
    "express-jwt": "~0.2.1",
    "jsonwebtoken": "~0.4.0",
    "socket.io": "^1.3.5",
    "socketio-jwt": "^3.0.0"

Thanks a lot for your time.

**Comment by jfromaniello** [comment]
Thats interesting, the token is validated on connection, but once the
connection is established the token is never verified again.

If you try to connect with an expired token you will get an error.

Should this module automatically close connections when the token expires?
I think the answer is no.

I think I can make an analogy like this: the id_token is like your national
passport , both have expiration, you can enter a country as long as your
passport is not expired and most  countries will not keep track of
expiration to hunt you down.

**Comment by jfromaniello** [comment]
I do think the application should have some way to enforce thia

**Comment by wang3g** [comment]
Thank you VERY MUCH for your prompt reply. Now everything makes sense. Previously, I thought for every incoming socket message, its token will get verified. Thanks again!

**Comment by danielchan303** [comment]
I have come up with a solution to handle the token expiration.

1. I set the AuthExpire timeout on the server when the the client is authenticated. This timeout will fired when the first submitted token is going to expire.

2. When timeout, server emit an event to request the client to submit a new token, and set a DisconnectTimeout that requires client to response within seconds else disconnect the user.

3. At the client side, the client will reply to the request to send new token.

4. Once the user submit the token, the server listen to the token submission event and will get the token, check the token. If the token is valid, set new authExpireTimeout, clear the disconnectTimeout to prevent disconnection. If the token is invalid, the disconnectTimeout will soon disconnect the client.

`var io = require("socket.io")(server);
const socketioJwt = require('socketio-jwt');
const jwt = require("jsonwebtoken");

const onGetToken = (socket) => {
  socket.on('token', (data) => {
    console.log("Socket.io: server get token from client");
    try {
      // validtate the token from client
      const tokenPayload = jwt.verify(data.token, process.env.SECRET);
      // token valid
      console.log("Socket.io: token from client is valid");
      // if the user re-authenticate successfully, don't disconnect
      clearTimeout(socket.disconnectTimeout);
      // create new reauthTimeout
      const tokenExpireIn = (tokenPayload.exp * 1000) - Date.now();
      console.log('Socket.io: new token expire in ', (tokenExpireIn / 1000 + ' s'));
      socket.authExpireTimeout = setAuthExpireTimeout(socket, tokenExpireIn);
    } catch (error) {
      // invalid or expired token
      console.log("Socket.io: invalid token for re-auth");
    }
  });
}

const setDisconnectTimeout = (socket) => {
  socket.disconnectTimeout = setTimeout(() => {
    // token is not sent from the user within 15s
    console.log("Socket.io: client does not re-auth within the specific time, disconnect him/her")
    socket.disconnect(true);
  }, 15000);
}

const setAuthExpireTimeout = (socket, tokenExpireIn) => {
  socket.authExpireTimeout = setTimeout(() => {
    // log
    console.log("Socket.io: last submitted token expire, need to reauth")
    // rquest the user to reauthenticate
    socket.emit('re-auth');
    // set the logoutTimeout, if client don't provide jwt or jwt expire, discoonect
    setDisconnectTimeout(socket);
  }, tokenExpireIn);
}

io.on('connection', socketioJwt.authorize({
  secret: process.env.SECRET,
  timeout: 15000 // 15 seconds to send the authentication message
})).on('authenticated', (socket) => {
  // this socket is authenticated, we are good to handle more events from it.
  console.log('Socket.io: authenticated');
  // handle re-authenticate
  const tokenExpireIn = socket.decoded_token.exp * 1000 - Date.now();
  console.log('Socket.io: the token will expire in ', (tokenExpireIn / 1000) + ' s');
  setAuthExpireTimeout(socket, tokenExpireIn);
  onGetToken(socket);

  socket.on('message', (data) => {
    console.log(data);
  });
});`
