### ISSUE TITLE
Unauthorised reasons for client

### ISSUE THREAD

**Issue by sakaenakajima** [auth0/socketio-jwt#39]
I'd like to have a way to know the reasons (invalid_token or timeout) for disconnection by unauthorised.

I have a situation where client gets unauthorised due to poor network connection. I'd like to my client to retry the authentication.

With the reasoning, I can have a logic like
if(reason=='invalid_token') return doLogout();
if(reason==='timeout') return doRetry();

**Comment by jfromaniello** [comment]
now it is supported, check #42
