### ISSUE TITLE
npm WARN deprecated jsonwebtoken@4.2.2: Critical vulnerability fix in v5.0.0.

### ISSUE THREAD

**Issue by edinella** [auth0/socketio-jwt#40]
See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by jfromaniello** [comment]
We wrote that blogpost and we fixed the vulnerability in this module  and jsonwebtoken before it was fixed on JWS. 

So, v3 of this module is not vulnerable even with a deprecated JWS dependency, but we are going to update it anyway to avoid the warning.

**Comment by edinella** [comment]
Thank you for the quick response, and congratulations for so useful open source projects.

**Comment by pose** [comment]
@edinella Fixed in `socketio-jwt@4.0.0`. Thanks for reporting!
