### ISSUE TITLE
Authorization only for a certain room or namespace

### ISSUE THREAD

**Issue by analytik** [auth0/socketio-jwt#45]
Hi,

I'd like to send both authorized and unauthorized data with one connection. E.g.
```
on connect:
  push public data
  if authorized:
    also push private data
```

Is this possible with the current implementation?

**Comment by jfromaniello** [comment]
This is possible now, check the latest version and this example:

https://github.com/auth0/socketio-jwt/blob/master/test/fixture/namespace.js

sorry for the delay
