### ISSUE TITLE
question: about example

### ISSUE THREAD

**Issue by martec** [auth0/socketio-jwt#46]
Sorry I could not understand the example.

```<input type="password" id="password" value="aaa" />``` of client side.
this is used for?
Or not matter login information of client side in this example?

i need check username and password inside ```app.post('/login', function (req, res) {``` correct?
if user found in db return token to user correct?
after return token to user, save this in localstorange? correct?
if user has token in localstorange so will bypass login text field? and automatically login this user? correct?
I need use passport module like this http://mherman.org/blog/2015/01/31/local-authentication-with-passport-and-express-4/#.VWruwUaWyEJ to check username and password? Or could made more simple way?

i can use publick key generated by PuTTYgen in secret key or publick key ?

**Comment by jfromaniello** [comment]
Yes for every question.

You can use passport-local but that's not necessary at all.
