### ISSUE TITLE
Possible missing return

### ISSUE THREAD

**Issue by bobiblazeski** [auth0/socketio-jwt#51]
I'm unable to use socketio-jwt with my koa app:   
Here's my code 
// Server 
 var io = SocketIo.listen(server);
    io.use(SocketIoJwt.authorize({
        secret: ServerConst.JWT_SECRET,
        handshake: true
    }));
    io.sockets
        .on('connection', function (socket) {
            console.log(socket.decoded_token.id, 'connected');
            socket.on('ping', function (m) {
                socket.emit('pong', m);
            });
        });
// Client 
function connect(token) {
    //var token = ClientStore.token.value;
    console.log('token',token);
    socket = io.connect(token ? ('?token=' + token) : '', {
        'forceNew': true
    });
    socket.on('pong', function () {
        console.log('- pong');
    }).on('time', function (data) {
        console.log('- broadcast: ' + data);
    }).on('authenticated', function () {
        setInterval(function () {          
            socket.emit('ping');
        }, 5000);
        console.log('- authenticated');
    }).on('disconnect', function () {
        console.log('- disconnected');
    });
}

I extracted below from https://github.com/auth0/socketio-jwt/blob/master/lib/index.js and it works OK 
Token.authorize = function authorize(data,accept){	
    var req = data.request || data;
	var token = req._query.token;
	var decoded = null;
	try {
		decoded = jwt.verify(token,ServerConst.JWT_SECRET);		
	} catch(err){
		console.log(err);
	}
	if(decoded) {
    data.decoded_token = decoded;
		return auth.success(data, accept);
	} else {
    return auth.fail('error', data, accept);
  }	 
}
 var auth = {
    success: function(data, accept){
      if (data.request) {
        accept();
      } else {
        accept(null, true);
      }
    },
    fail: function(error, data, accept){
      if (data.request) {
        accept(error);
      } else {
        accept(null, false);
      }
    },
    secret: ServerConst.JWT_SECRET,
    handshake: true
  };
// Usage
io.use(Token.authorize);

I'm little confused why you don't use return statement at line 141  auth.success(data, accept);

**Comment by pieterjandesmedt** [comment]
Good catch. I had the same problem. 
I created a PR #58 to fix this.
