### ISSUE TITLE
Capturing authentication error on the server

### ISSUE THREAD

**Issue by soichih** [auth0/socketio-jwt#54]
I am using this method to authenticate incoming socket.io connection

```
io.sockets
  .on('connection', socketioJwt.authorize({
    secret: 'your secret or public key',
    timeout: 15000 // 15 seconds to send the authentication message
  })).on('authenticated', function(socket) {
    //this socket is authenticated, we are good to handle more events from it.
    console.log('hello! ' + socket.decoded_token.name);
  });
```

It works, but if user provides me an invalid (expired, corrupted, etc..) jwt token, I want to log that event on the server side (and probably emit error to the client to let user know that they need to re-login).  

How can I receive error object from authorize()?

**Comment by jfromaniello** [comment]
@soichih you can listen to the `unauthorized` event

**Comment by mypark** [comment]
Do you have an example?  I tried

```
 io
    .on('connection', socketioJwt.authorize({
      secret: 'test',
      required: true,
      timeout: 7000 
    }))
    .on('unauthorized', (error) => {
      console.log(error);
    })
```

but that didn't trigger

**Comment by soichih** [comment]
I just confirmed that "unauthorized" event doesn't fire if I provide a bogus jwt on the latest version of socketio-jwt (4.3.3)

**Comment by kelvien** [comment]
I also don't know how to capture the error on server-side. 
But for client-side, do this:
`socket.on('unauthorized', function(data, callback){
    console.log(data); // This error message is for client-side
    callback(); // This is to disconnect yourself (Optional)
});`

**Comment by asadsahi** [comment]
having same issue, unauthorized isn't firing.

**Comment by hugomallet** [comment]
I found a solution, wrap the default middleware

```js
io.use((socket, next) => {
	const nextWrapper = (error) => {
		if (error) {
			// Do what you want
			console.log('error', error);
		}
		next(error);
	};
	return authorize(socket, nextWrapper);
})
```
