### ISSUE TITLE
How can we get token (not decoded)?

### ISSUE THREAD

**Issue by metanav** [auth0/socketio-jwt#56]
Is there any way to get the original token sent by client?
I need to reuse it.

**Comment by Hirbod** [comment]
Actually you should know it, as you have to emit it to node ?

**Comment by chrene** [comment]
@metanav you can retrieve the token from the sockets handshake object.
If your token is called `token` when you send it from the client the following should `console.log` your token.
```
    io.on('connection', (socket) => {
      console.log('token: ', socket.handshake.query.token)
   }
```
