### ISSUE TITLE
One roundtrip doesn't work

### ISSUE THREAD

**Issue by Ethefor** [auth0/socketio-jwt#79]
I am trying to use **one roundtrip**, but it seems not to work. 

In browser it seems everything to be ok:
`http://localhost:3000/socket.io/?token=JWT%20eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1NmU4NjJkMzdlMmI0NmQ5NjkxZmE5MTgiLCJuYW1lIjoicSIsIl9fdiI6MH0.8qBoqlSjpymgQFU_DcVPLM5VcuOqOThH96AA99wpxVY&EIO=3&transport=websocket&sid=QpwxBPrxpQn3iGX3AAAC`
As you see above JWT is provided, but on the server side nothing happens... 

**How can I debug my code to determine what is wrong?** 
I inserted `console.log('Function authorize')` in _socketio-jwt index.js_ file, and this is printed out to console just after restarting the server (so I guess, that I loaded _socketio-jwt_ correctly). But after authenticating on server nothing happens (no errors etc.) I also check that I have connection with server, because, when I shut down the server, on browser start to fetching socket.io constantly, and after restarting server browser gets connected. But authentication doesn't work... 
Any help greatly appreciated, because I don't know if this is a bug in socketio-jwt or I am doing something wrong.

**Comment by Ethefor** [comment]
I didn't realize that I must insert something like:
```
socket.on("error", function(error) {
    alert(error.type + '\n' + error.message + '\n' + error.code);
});
```
on the client side to see the error.
But the error message is simply **invalid token**, without any further information. This is strange for me, because I did not even see in source code of _socketio-jwt_ such message for _invalid_token_ code (I see only _invalid token datatype_,  _jwt must be provided_, _jwt malformed_ or _jwt signature is required_), but I get simply **invalid token** message... What am I doing wrong? 

Maybe we can add information in README.md about types of error that may occur and how to handle it?

**Comment by Ethefor** [comment]
OK, never mind, my mistake. I provided token:
`JWT%20eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1NmU4NjJkMzdlMmI0NmQ5NjkxZmE5MTgiLCJuYW1lIjoicSIsIl9fdiI6MH0.8qBoqlSjpymgQFU_DcVPLM5VcuOqOThH96AA99wpxVY`
with additional 'JWT ' before.

Token must be provided without string like 'JWT ':
`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1NmU4NjJkMzdlMmI0NmQ5NjkxZmE5MTgiLCJuYW1lIjoicSIsIl9fdiI6MH0.8qBoqlSjpymgQFU_DcVPLM5VcuOqOThH96AA99wpxVY`

Now everything works like a charm :)

**Comment by jfromaniello** [comment]
Thanks for the explanation and following up!

Is there something in the README wrong?

**Comment by Ethefor** [comment]
Everything with README is ok, but maybe it is possible to provide more information about showing and handling errors. For me it was unobvious that this errors doesn't appear in console on the server side, but only on client side.
