### ISSUE TITLE
Any have any experience on how to emit the token from IOS/swift?

### ISSUE THREAD

**Issue by arashdoescode** [auth0/socketio-jwt#88]
It's been 4 hours, but for somehow I couldn't fix this problem, I can't send the token to the server no matter what I do

Serverside code

```
io.use(socketioJwt.authorize({
  secret: config.SECRET,
  handshake: true
}));

  io
    .on('connection', function(socket) {

    
  })
   .on('authenticated', function(socket){
   console.log('connected & authenticated: ' + JSON.stringify(socket.decoded_token));
    socket.on('onJob', function(data) {
      console.log(data);
    });
});

```

Client-side code - IOS/SWIFT

```
import SocketIOClientSwift
import KeychainAccess

class SocketIOManager: NSObject {
    static let sharedInstance = SocketIOManager()
    
    let socket = SocketIOClient(socketURL: NSURL(string: "https://testing.herokuapp.com")!,
                                                     options: [.Log(true)])
        
    override init() {
        super.init()
        
    }
    
    
    func establishConnection(token: String) {
        socket.on("connection") {data, ack in
            self.socket.emit("authenticated", token);
        }
    }

    func closeConnection() {
        socket.disconnect()
    }
    
    func genieOnJob(lat: String, long: String) {
        socket.emit("genieOnJob", lat, long)
    }
    
    
}

```

So technically whenever someone tap a button on the clientside, then I will call establishConnection and provide with a token.

Anyone have any experience on how to fix this problem?

**Comment by DiknT** [comment]
looks like you mixed up the auth flows. On the server-side you are setting handshake:true which then expects the token to be sent as querystring or as authorization-header on connection attempt. But on the client-side you are using the second-roundtrip method, which is sending the token upon connection with socket.emit('authenticate', token), which you also misspelled as 'authenticated', which is the event the client receives upon successful authentication with the second-roundtrip event. hope this helps

**Comment by arashdoescode** [comment]
Could i sent it via header, I meant the token, when i instantiate the header?

**Comment by arashdoescode** [comment]
I wrote a SO post http://stackoverflow.com/questions/37549701/secret-or-public-key-must-be-provided-ios-swift-socket-io-jwt

If you could help me.

**Comment by arashdoescode** [comment]
Solved it

**Comment by nithinreddygaddam** [comment]
Hi May I know how you solved it?
