### ISSUE TITLE
Please update the decoded_token

### ISSUE THREAD

**Issue by jackalsin** [auth0/socketio-jwt#99]
Currently, the socket.decoded_token has changed the structure
Now, it will look like this
```
{$__: 
    {"key": "Value"},
"_doc": {
    "real key":"real value"
    }

}
```
Therefore, `socket.decoded_token.name` will on longer work. 

By the way, awesome project!

**Comment by jfromaniello** [comment]
I think this doesn't have to do with this project, but maybe with the way you are signing tokens. 

Can you show me an example token?

**Comment by jackalsin** [comment]
Yeah, you are right ... It's kind of related to Mongoose. I use a mongoose model as payload. Sorry for this.
I never used the jwt without a database... My bad

**Comment by jfromaniello** [comment]
No problem! in that case try this when generating the token:

```javascript
jwt.sign(doc.toObject(), secret);
```

I have never used mongoose but I have helped someone with the same problem few months ago.

https://github.com/auth0/node-jsonwebtoken/issues/156#issuecomment-169035175
